# Generated by Django 2.1.7 on 2019-02-28 18:37

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update_manager', '0005_updaterlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updaterlist',
            options={'verbose_name': 'user updater', 'verbose_name_plural': 'User updaters'},
        ),
        migrations.AlterField(
            model_name='updaterlist',
            name='updaters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='updaterlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
