# Generated by Django 2.1.7 on 2019-02-28 18:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import update_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('update_manager', '0006_auto_20190228_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeutronApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True)),
                ('branches', django.contrib.postgres.fields.jsonb.JSONField(default=update_manager.models.default_branches)),
                ('components', django.contrib.postgres.fields.jsonb.JSONField(default=update_manager.models.blank_components)),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
