# Generated by Django 2.1.7 on 2019-02-28 19:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update_manager', '0007_neutronapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versions', django.contrib.postgres.fields.jsonb.JSONField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='update_manager.NeutronApplication')),
            ],
            options={
                'verbose_name': 'application version',
                'verbose_name_plural': 'Application versions',
            },
        ),
    ]
