# Generated by Django 2.1.7 on 2019-02-28 19:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_manager', '0008_versioncontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncontrol',
            name='versions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
