# Generated by Django 2.1.7 on 2019-03-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_manager', '0010_versioncontrol_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='versioncontrol',
            name='changelog',
            field=models.TextField(blank=True),
        ),
    ]
