# Generated by Django 2.1.7 on 2019-03-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_manager', '0013_mqttacl_mqttusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mqttacl',
            options={'verbose_name': 'mqtt access control', 'verbose_name_plural': 'MQTT ACLs'},
        ),
        migrations.AlterModelOptions(
            name='mqttusers',
            options={'verbose_name': 'mqtt user', 'verbose_name_plural': 'MQTT Users'},
        ),
    ]
