# Generated by Django 2.1.7 on 2019-03-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_manager', '0014_auto_20190311_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttacl',
            name='rw',
            field=models.IntegerField(default=5),
        ),
    ]
