# Generated by Django 2.1.7 on 2019-03-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_manager', '0016_auto_20190312_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttusers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
